### ISSUE TITLE
Do not require privacy policy popup

### ISSUE THREAD

**Issue by cweiske** [calcitem/Sanmill#218]
It would be nice if the user would not have to agree to the privacy policy.

Sanmill on android is a local-only game, so there should not be any need for a policy.
If it is only needed for crash reports, then the crash report submit screen should let the user agree to it.

Apart from that, modifying the terms of services/privacy policy without notifying the user is illegal in some countries, so simply stating that it changes from time to time and that the user has to look at it on his own is wrong.

**Comment by calcitem** [comment]
Thank you for reporting this bug.  In the next version, unless the locale is Chinese, the privacy statement dialog box will not pop up.  According to China's information security laws, regardless of whether an App is connected to the Internet, a privacy statement dialog box must be popped up when it is first run. This is a requirement for publishing in the domestic application market in China. 

In fact, the Chinese text is as follows:

```
请您务必审慎阅读、充分理解《隐私政策》各条款，包括但不限于：为了改善我们向您提供的服务，基于您的明示授权，我们可能会获取您的设备型号、诊断数据、电子邮件地址等信息，您有权拒绝或取消授权。我们将在每次请求发送诊断数据前，通过弹窗形式征得您的明示同意。您可阅读了解详细信息。如您同意，请点击“同意”开始接受我们的服务。
```
Translated into German is as follows:

```
Bitte lesen Sie die Bedingungen der "Datenschutzrichtlinie" sorgfältig durch und verstehen Sie sie vollständig, einschließlich, aber nicht beschränkt auf: Um die von uns bereitgestellten Dienste basierend auf Ihrer ausdrücklichen Genehmigung zu verbessern, können wir Ihr Gerätemodell, Diagnosedaten und E-Mails abrufen Adresse und andere Informationen haben Sie das Recht, die Genehmigung zu verweigern oder zu widerrufen. Vor jeder Anfrage zum Versand von Diagnosedaten holen wir Ihre ausdrückliche Einwilligung durch ein Pop-up-Fenster ein. Sie können für Details lesen. Wenn Sie damit einverstanden sind, klicken Sie bitte auf "Zustimmen", um unseren Service zu akzeptieren.
```

And because our native language is not English, it cannot be accurately translated into English, so we refer to the text of an App, but did not consider this legal risk. Thanks for pointing out!
