### ISSUE TITLE
Menu UI problem with Persian language

### ISSUE THREAD

**Issue by iJahangard** [calcitem/Sanmill#239]
The game translated to Persian 100 percent
Awesome
But there's an small problem with right to left languages in menu of the game

![Screenshot](https://user-images.githubusercontent.com/67248292/123717574-5fdbd780-d892-11eb-890d-47c516a1dd06.jpg)

I have / had this issues with some other applications which they have menu UI like your app's menu
Like material files , oto music ...

Hope will be fixed the app looks pretty
~~BTW I can't see option to manually select the language
I use in English in most times for system language
But for this game i like see my language

Thank in advance~~

**Comment by iJahangard** [comment]
I just update the app from play store 
That early build ! 
I got the ability to choose language

Seems menu UI look better (not enough) when your system language is English and app language is Persian
![Screenshot](https://user-images.githubusercontent.com/67248292/123718669-0923cd00-d895-11eb-8904-30a6abac04dd.jpg)

**Comment by iJahangard** [comment]
But as you can see the menu is in left of display
That is why UI looks fine with secondary situation

**Comment by calcitem** [comment]
Thank you for your feedback!  

When the system language is English and the App language is Persian or Arabic, the layout is not from right to left. This problem seems difficult to solve because the program is required to read the configuration at the beginning to determine the layout, it is difficult to read the language configuration during initialization.  I will look for a solution again this week.  

Unfortunately, it is difficult to find Persian apps based on Flutter at present, and it is also difficult for me to search for the technical information needed in Persian.  If you know the Flutter open source program that supports Persian language for reference, welcome to recommend.  

In addition, the Persian language of this App is machine translation. There should be many inaccurate translations. If you are interested, welcome to join our translation project, thank you very much!

**Comment by calcitem** [comment]
Our translation project:
https://github.com/calcitem/Sanmill/issues/231

**Comment by calcitem** [comment]
Sorry, I don’t seem to understand your original question. Regarding the menu UI question, I wonder if you can describe it in Persian in detail. I will try to translate it into Chinese by machine to see if I can understand what you mean, thank you#

**Comment by calcitem** [comment]
Do you mean that the length of the highlight bar of the menu item is not long enough, and one side is not in the shape of an arc, so it is not pretty?

**Comment by iJahangard** [comment]
> Thank you for your feedback!  
> 
> When the system language is English and the App language is Persian or Arabic, the layout is from left to right. This problem seems difficult to solve because the program is required to read the configuration at the beginning to determine the layout, it is difficult to read the App's language option during App initialization.  I will look for a solution again this week.
> 
> In addition, the Persian language of this App is machine translation. There should be many inaccurate translations. If you are interested, welcome to join our translation project, thank you very much!
> 
> Our translation project:
> https://github.com/calcitem/Sanmill/issues/231

This one is not a bug , **it is a feature **😂
Dont suffer yourself do solve this

Mine problem is about : when system and the game languages are Persian (so layout is rtl just like first screenshot)

**Comment by iJahangard** [comment]
> In addition, the Persian language of this App is machine translation. There should be many inaccurate translations. If you are interested, welcome to join our translation project, thank you very much!
For a machine translation it is good really maybe Chinese and persian have same meaning connections LMAO 😂

 I really like to help with translations
Will do if I have time ,soon..

> Our translation project:
> https://github.com/calcitem/Sanmill/issues/231
 
Will check this out ;)

**Comment by iJahangard** [comment]
> Do you mean that the length of the highlight bar of the menu item is not long enough, and one side is not in the shape of an arc, so it is not pretty?

I mean yeah...
Layout is RTL but highlight-bar stuck in the other mode (LTR)

THAT'S all of my problem is about! 
Remember ! _When system and app language are Persian (or any RTL) !
_
System is LTR and app RTL is all fine
No need any fix

**Comment by iJahangard** [comment]
> Especially the following lines are not clear, my mother tongue is not English.  So can you add a detailed description?  Thank you!
> 
> ```
> I have / had this issues woth some other app that use such as this menu ui
> Like material files , oto music ...
> ```
 
I edited the passage , anyway those line are not really important , nothing especial

**Comment by calcitem** [comment]
Thanks for the explanation. It seems that the bug is easier to fix. If it goes well, the updated version can be repaired.  In addition, if the interface is in Persian but the layout is not from right to left, will Iranian users find it strange?  In addition, for the proofreading of the translation, if you have time, you can also download the following files to modify and submit, thank you very much!

https://github.com/calcitem/Sanmill/blob/master/src/ui/flutter_app/lib/l10n/intl_fa.arb

The machine translation of Persian is from English, so it seems that the expressions of Persian and English are similar, which is an unexpected surprise.

**Comment by iJahangard** [comment]
> Thanks for the explanation. It seems that the bug is easier to fix. If it goes well, the updated version can repair it.  In addition, if the string is in Persian but the layout is not from right to left, will Iranian users think it strange?
> 
No! not at all! It's fine ! but you know a design should have appropriate implement! We right stuff from right to left , icons should be in right side alike menu

The app doesn't seem have big problem all is about a highlight bar(whatever is its name) tha need a horizontal flipping to fix a simple UI problem

LTR layout will be fine when the system is English and app is Persian it looks like secondary screenshot

RTL layout with Persian for both system and app will be fixed when you do some code for that highlight bar
That's it !
Thank in advance

> In addition, for the proofreading of the translation, If that translation site is confusing, and if you have time, you can also download the following files to modify and make a PR or simply send to me, thank you very much!
> 
I figured it out how to use the site try edit some translations
> https://github.com/calcitem/Sanmill/blob/master/src/ui/flutter_app/lib/l10n/intl_fa.arb
> 
> The machine translation of Persian is from English, so it seems that the expressions of Persian and English are similar, which is an unexpected surprise.
> 
😬 Uhh ! I remember the days that translate machine completely messed up with translate English to Persian! So maybe they more powerful now ! This is weird & really is an unexpected surprise
😅

**Comment by calcitem** [comment]
Understand, I will keep the LTR layout when the system language is English, and only fix the display problem of the highlight bar.  

Currently, Mill App only has German, Hungarian and Romanian languages ​​that have been translated and proofread by contributors. It looks like Persian is expected to be the next one. Thanks to your efforts, I will include you in the list of contributors.  Haha!
