### ISSUE TITLE
Options arrows and navigation buttons issues in RTL languages

### ISSUE THREAD

**Issue by iJahangard** [calcitem/Sanmill#241]
In app settings and personalization in an RTL language the arrows should be flipped horizontally to look correctly
![IMG_۲۰۲۱۰۶۳۰_۱۴۴۹۰۴.jpg](https://user-images.githubusercontent.com/67248292/123944434-5b0e4500-d9b2-11eb-858b-45a142b09683.jpg)

Also with navigation buttons enabled : 
Buttons should not be flipped horizontally because 
People with LTR and RTL think similar 
Back button is always in left side and forward is in right side !
So now ,in the app, people who have an RTL lang. Will be confused with this navigation area

https://user-images.githubusercontent.com/67248292/123945156-16cf7480-d9b3-11eb-8129-cd8a11f466bd.mp4

I want to go back and it will go forward 😂
And want to clear by back to first move and nothing will happen because you are in last movement

BTW i have to say there is no problem with when system language is LTR and app is RTL

**Comment by calcitem** [comment]
Thank you for your valuable suggestions! In addition, does the order of the toolbars - Game/Option/Move/Info need to be arranged from right to left?
________________________________
From: iJahangard ***@***.***>
Sent: Wednesday, June 30, 2021 6:26:48 PM
To: calcitem/Sanmill ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [calcitem/Sanmill] Options arrows and navigation buttons issues in RTL languages (#241)


In app settings and personalization in an RTL language the arrows should be flipped horizontally to look correctly
[IMG_۲۰۲۱۰۶۳۰_۱۴۴۹۰۴.jpg]<https://user-images.githubusercontent.com/67248292/123944434-5b0e4500-d9b2-11eb-858b-45a142b09683.jpg>

Also with navigation buttons enabled :
Buttons should not be flipped horizontally because
People with LTR and RTL think similar
Back button is always in left side and forward is in right side !
So now ,in the app, people who have an RTL lang. Will be confused with this navigation area

https://user-images.githubusercontent.com/67248292/123945156-16cf7480-d9b3-11eb-8129-cd8a11f466bd.mp4

I want to go back and it will go forward 😂
And want to clear by back to first move and nothing will happen because you are in last movement

**Comment by calcitem** [comment]
Thank you for your valuable suggestions! In addition, does the order of the toolbars - Game/Option/Move/Info need to be arranged from right to left?

**Comment by iJahangard** [comment]
> does the order of the toolbar's buttons - Game/Options/Move/Info need to be arranged from right to left?
> Nope! They are fine

**Comment by calcitem** [comment]
For the current RTL layout, at the top of the page, suppose that humans move first, and AI moves second. Then human icon are displayed on the right and AI icon is displayed on the left. Is the direction of this icon right?  Thank you!

**Comment by iJahangard** [comment]
> For the current RTL layout, at the top of the page, suppose that human move first, and AI moves second. Then human icon are displayed on the right and AI icon is displayed on the left. Is the direction of this icon right?  Thank you!

Those icons are right but i guess arrow have problem (not sure) 
When it is my turn it's like this :  💻 > 👴
Idk if it's correct appearance

But i think it's not a good way to show it who's turn
BTW what's that creamy line means ,it just an unnecessary element
I guess we should have to icons for player 1&2 
Whit a circle that moves depend on which player have to place a piece
Then you have good UI that no need any fix based on languages


BTW you used material filled icon in menu and material outline in board 
They are inconsistent google guantium is a good material icons which google use in their apps
I can collect and send them as xml vector drawable to you! If you want!

**Comment by calcitem** [comment]
> Those icons are right but I guess the arrow has the problem (not sure)
> When it is my turn it's like this : 💻 > 👴
> Idk if it's correct appearance
>
> But I think it's not a good way to show it who's turn

So it is correct to say that when using the RTL layout, the icon corresponding to the first player should be on the right and the icon corresponding to the second player on the left?

I'm not sure if this is correct either, haven't seen this representation in other gaming-type programs and don't have a reference object. Because the AI moves very fast at low levels of difficulty, players will see a circle on the 👴 icon 99% of the time and 💻 is not circled, which feels like it might not be very pretty, so this arrow is used to indicate which player's turn to move.

>BTW what's that creamy line means, it just an unnecessary element
>I guess we should have icons for players 1 and 2
>Which circle that moves to depend on which player has to place a piece
>Then you have a good UI that no need any fix based on languages

Without that line, the icons and hint text put together is not sure whether it is beautiful, may not simply remove the line can solve the problem, may need to redesign the whole layout.

> BTW you used material filled icon in the menu and material outline inboard
> They are inconsistent google quantum is a good material icon that Google uses in their apps
> I can collect and send them as XML vector drawable to you! If you want!

You mean either use filled icons for all icons or use outline icons for all icons, just to be consistent
If I want to use vector graphics, I may need to integrate https://pub.dev/packages/flutter_svg before I can apply vector graphics. You can collect and send it to me first.

**Comment by iJahangard** [comment]
> So it is correct to say that when using the RTL layout, the icon corresponding to the first player should be on the right and the icon corresponding to the second player on the left?
> 
Yes it's fine

> I'm not sure if this is correct either. I haven't seen this representation in other gaming-type programs and don't have a reference object. Because the AI moves very fast at easy levels of difficulty, players will see a circle on the 👴 icon 99% of the time and 💻 is not circled, which feels like it might not be beautiful, so this arrow indicates which player's turn to move.
> 
I guess so ! **>👴** Shows human turn , right? Ofc. In RTL 
And in RTL it shows like **👴<**
So i understand there is no problem of that arrow and icons
> 
> Without that line, the icons and hint text put together is not sure whether it is beautiful, may not simply remove the line can solve the problem, may need to redesign the whole layout.
> 
Guess what !? 😂 You can set the color of the line to #00000000 (fully transparent)

So then it is still ugly ! As I mentioned you can use a circle with with a cool animation that specify which player most do actions

For design I think circle should be 48dp with icon 24dp(as always)

> You mean either use filled icons for all icons or use outline icons for all icons to be consistent
> 
I mean use icons that I will send you (they are material outline) haha 😂😂😂 
They are google material icons

> If I want to use vector icons, I may need to integrate https://pub.dev/packages/flutter_svg before applying vector icons. You can collect and send it to me first if you have time.
>
I will collect them and send , you can see them with a chrome extension ,and decide if you want to use them!
I am a designer (kind of! 😅 Also a themer) I'm familiar with material design too 
so will send you a collection of comfortable icons with no need fix in xml format, you just replace (as long as you didn't set color values within the xml files of icons

**Comment by calcitem** [comment]
The guidance of language expert + UI designer + programmer full-stack engineer is very cool!

The original issue of this Issue has been fixed. You can download a new APK at https://github.com/calcitem/Sanmill/actions/runs/987109431 to see the effect. 
(Due to the signing key difference, you need to uninstall and then install)

**Comment by iJahangard** [comment]
> The guidance of language expert + UI designer + programmer full-stack engineer is very cool!
> 
Thank you but I am too young to be a full-stack engineer, need a lot of experience
Also I try to improve my English , at least I can say I'm a UI designer and a good themer
And I have good ideas :)
> The original layout problem of this Issue has been fixed. You can download a new APK at https://github.com/calcitem/Sanmill/actions/runs/987109431 to see the effect. 
> (Due to the signing key difference, you need to uninstall and then install)
> 
I patched my system ,no need to uninstall anything haha


Anyway navigation buttons ,menu UI , arrows are all fine now

But there's one simple thing:
![Screenshot_۲۰۲۱-۰۶-۳۰-۲۱-۵۴-۱۲-۰۶۱_com.calcitem.sanmill_1.jpg](https://user-images.githubusercontent.com/67248292/124014897-5751e100-d9f9-11eb-84c4-f4ec040c3bb4.jpg)
![Screenshot_۲۰۲۱-۰۶-۳۰-۲۱-۵۳-۵۹-۰۰۳_com.calcitem.sanmill_1.jpg](https://user-images.githubusercontent.com/67248292/124014961-66d12a00-d9f9-11eb-9cd8-6a245a0769e0.jpg)
![Screenshot_۲۰۲۱-۰۶-۳۰-۲۱-۵۵-۲۱-۵۲۷_com.calcitem.sanmill_1.jpg](https://user-images.githubusercontent.com/67248292/124014976-6a64b100-d9f9-11eb-9545-3a94bc255232.jpg)
1. You created a gap (padding) there (basically any where an arrow exist)
2.3.4. the color box , language , numbers should be in the right of arrows not left of them!

**Comment by calcitem** [comment]
Thanks for pointing out, the remaining issues will be fixed tomorrow!

Looking forward to your new design! 
A new issue can be opened at that time

**Comment by calcitem** [comment]
> You created a gap (padding) there (basically anywhere an arrow exist)
> 2.3.4. the color box, language, numbers should be in the right of the arrows, not the left of them!

Thanks! This problem is fixed, new apk can be downloaded from:
https://github.com/calcitem/Sanmill/actions/runs/990891382

**Comment by iJahangard** [comment]
> Thanks! This problem is fixed
>
Oh yeah! Everything looks great now,
I can see the translations are fine too
Thank you
