### ISSUE TITLE
Arabic translation

### ISSUE THREAD

**Issue by islam2hamy** [calcitem/Sanmill#280]
<a href="https://ibb.co/VVPJBF8"><img src="https://i.ibb.co/Q91pmWG/ac845910-ead0-4330-a9f9-de5e493ab551.jpg" alt="ac845910-ead0-4330-a9f9-de5e493ab551" border="0"></a><br /><br />

**Comment by calcitem** [comment]
Please check the rule settings, click the icon in the upper right corner to open the right menu, and then enter the rule settings. If the flying rule is enabled, the behavior is as expected. In addition, if possible, please help to collect a copy of the mill game rules of Arab countries so that we can customize the default rules for Arabic users. Thank you!

الرجاء التحقق من إعدادات القاعدة ، انقر فوق الرمز الموجود في الزاوية اليمنى العليا لفتح القائمة اليمنى ، ثم أدخل إعدادات القاعدة. إذا تم تمكين قواعد الرحلة ، يكون السلوك كما هو متوقع. بالإضافة إلى ذلك ، إذا أمكن ، الرجاء المساعدة في جمع نسخة من قواعد الدول العربية حتى نتمكن من تخصيص القواعد الافتراضية للمستخدمين العرب. شكرًا لك!

**Comment by islam2hamy** [comment]
flying rule is enabled ، 
Thank you.

I have updated the Arabic translation
Please check it

**Comment by calcitem** [comment]
> I have updated the Arabic translation
> Please check it

Thank you!!

Applied, new apk: https://github.com/calcitem/Sanmill/actions/runs/1270816194

**Comment by islam2hamy** [comment]
Arabic translation updated again

**Comment by calcitem** [comment]
> Arabic translation updated again

May I know why do you delete an item? -- Source code

**Comment by calcitem** [comment]
Thank you for improving the Arabic translation. 

I have responded to the questionable translation on https://poeditor.com/, and you may receive multiple emails. 

Thanks!

**Comment by islam2hamy** [comment]
> > Arabic translation updated again
> 
> May I know why do you delete an item? -- Source code
> 
> I restored it.

Sorry it was by mistake

**Comment by islam2hamy** [comment]
> Thank you for improving the Arabic translation.
You are welcome
> 
> I have responded to the questionable translation on https://poeditor.com/, and you may receive multiple emails.
> 
> Thanks!

I didn't ask any question there

However i will update it again after finding wrong translation while playing

**Comment by calcitem** [comment]
Thank you!

If you have any questions, you can leave comments on https://poeditor.com/.

**Comment by islam2hamy** [comment]
Ok

**Comment by calcitem** [comment]
APK updated:  https://github.com/calcitem/Sanmill/actions/runs/1272780425

**Comment by calcitem** [comment]
Please continue to correct the Arabic translation of the new function on weblate in the future, thank you!  This issue is closed first.
