### ISSUE TITLE
The default algorithm should be MTD(f)

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#419]
The default algorithm should be MTD(f), not Alpha-Beta.

Thanks!

**Comment by Leptopoda** [comment]
the defualt algorythm is mdtf
https://github.com/calcitem/Sanmill/blob/cf64453a001958fbf277a1bf34ef04f03a0d2b97/src/ui/flutter_app/lib/models/preferences.dart#L75

where did you see that error? Did something go wrong with the migration?
Also I think the issue is related to the currently open PR so we should discuss it there and not here...

**Comment by calcitem** [comment]
> Did something go wrong with the migration?

Maybe it is. I try to restore the default settings. It's MTD(f), no problem.

**Comment by Leptopoda** [comment]
any news on this one?

**Comment by calcitem** [comment]
We can solve the crash problem first, and then return to the test case.  I found that all kinds of strange abnormalities will appear after the crash.

**Comment by Leptopoda** [comment]
any news on this?

**Comment by calcitem** [comment]
Both https://github.com/calcitem/Sanmill/actions/runs/1538568762 and branch dev have this bug.

**Comment by calcitem** [comment]
Not bisect yet. Need me bisect?

**Comment by Leptopoda** [comment]
Ok i think i know what happens here...

When the storage get's reset on the android side (not inside the app) the app will assume (on first start) that you still use the json style settings thus running the migration and somehow setting alpha-beta as the default...
