### ISSUE TITLE
Can't set AI difficulty level

### ISSUE THREAD

**Issue by Duvio** [calcitem/Sanmill#819]
**Describe the bug**
When dragging the difficulty level slider, nothing happens.

**To Reproduce**
1. Start an Human vs AI game
2. Click on Options
3. Click on difficulty level
4. Try dragging the slider

**Expected behavior**
The slider to slide and the difficulty level to change accordingly.

**Screenshots**
![Screenshot_20240531-024913_Mill](https://github.com/calcitem/Sanmill/assets/29256280/9c45a9bf-ee59-41c1-9303-ce21b92a761d)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A52s 5G
 - OS: Android - LineageOS
 - Version: 21

**Comment by calcitem** [comment]
Thank you for reaching out and providing detailed feedback. We understand that certain unexpected issues can arise when using Flutter on LineageOS, as similar display-related problems have been reported by other users as well. Upon investigation, these issues generally require resolution from the Flutter development team.

We recommend updating your app to the latest version, which utilizes the most recent Flutter framework. This update may potentially resolve the issue you are experiencing. If the problem persists after the update, we will consider replacing the widget and kindly ask for your assistance in verifying the solution.

Thank you for your understanding and cooperation.

**Comment by calcitem** [comment]
Thank you for reporting this issue with the difficulty level slider in the Sanmill app. I appreciate your detailed description and the steps you provided.

I have attempted to reproduce the issue on a Google Pixel 3a XL running LineageOS 21 to ensure it mirrors your experience as closely as possible. Interestingly, when I manually installed the APK, the slider worked as expected, and I did not encounter the bug you described. This suggests that the issue might be specific to certain configurations or versions of LineageOS.

Additionally, I faced challenges in accessing the app from Google Play Store on the LineageOS device due to compatibility issues, which might indicate a broader issue with how the app is recognized by Google Play on custom ROMs like LineageOS. However, on a standard Android 14 device, the app was accessible and functioning correctly.

Could you please confirm if you were able to download the app directly from Google Play or another source such as F-Droid? This information might help us understand how widespread the issue is and whether it's isolated to Google Play installations.

In the meantime, I am reaching out to both the LineageOS and Flutter communities for more insights and potential solutions, as it seems there might be a compatibility issue affecting the app on LineageOS. You can track or contribute to the discussion [here on Stack Overflow](https://stackoverflow.com/questions/78562746/compatibility-issue-with-flutter-apps-on-lineageos-21).

Thank you once again for your patience and for helping us improve Sanmill. Any additional information you can provide would be greatly appreciated.

**Comment by Duvio** [comment]
Thank you for your detailed response and for investigating the issue further.

Regarding the Google Play Store, the app does not appear for me either. When I navigate to it manually, I'm unable to install it due to a red error message indicating that the app is incompatible with my device. However, I successfully installed the app from F-Droid without any issues. If i hadn't found the app on F-Droid, i would likely not know that it existed. In my opinion, this is the best Mill app available on the entire market. Even when explicitly searching for "Mill" on the Google Play Store, this app isn't recommended/shown at all. This lack of visibility likely means that many potential users are missing out, significantly limiting the app's reach.

As for the original issue, I have discovered that the difficulty level slider is actually a number picker/horizontal scrolling wheel. Initially, I couldn't see the numbers because I had dark theme enabled, which caused the numbers to disappear. When I disabled dark theme, the numbers became visible as expected. This suggests that the issue is indeed related to Flutter's handling of dark themes.

The screenshot in my original bug report has been taken with dark theme enabled.
The screenshot in the following image has been taken with dark theme disabled.
![Screenshot_20240601-062312_Mill](https://github.com/calcitem/Sanmill/assets/29256280/18b3bab0-cd5e-463a-9271-5f39a4e1c5b4)

**Comment by calcitem** [comment]
Thank you, Duvio, for your detailed feedback and continued engagement. We are committed to improving Sanmill and appreciate your assistance in identifying these issues.

We have noted the problem with the number picker/vertical scrolling wheel in dark mode and are [prioritizing a fix](https://github.com/calcitem/Sanmill/commit/3b401badb644ad1486152faa4ca8cc4d3718042c) in our next release to ensure numbers are visible in all themes, including dark mode. A comprehensive adaptation for dark mode is planned for the future to enhance user experience across all settings.

Initially, I was quite alarmed when I couldn't find the Sanmill app in the Play Store, fearing it might have been delisted due to a violation. Thankfully, that was not the case. We are aware that although Sanmill is currently one of the top two Mill apps on the market, with a rating of around 3.7-3.9, there is significant room for improvement. We are committed to elevating the quality of Sanmill to ensure it stands out as the best Mill app available.

We value our LineageOS users highly, recognizing them as discerning players who share our dedication to privacy and security. Rest assured, we are taking this issue seriously and are actively investigating to resolve it swiftly.

Interestingly, we found that installing the [Aurora Store](https://f-droid.org/packages/com.aurora.store/) via F-Droid allows the Sanmill app to be searchable within Aurora, which is a curious phenomenon. We are exploring this further to understand and rectify the visibility issues on different platforms.

Thank you once again for your patience and for helping make Sanmill better. Your insights are invaluable to us, and we look forward to continuing to improve the app together.

**Comment by calcitem** [comment]
We have discovered an intriguing new phenomenon regarding the visibility of Sanmill in the Google Play Store. When the user join our internal testing program through this link: https://play.google.com/apps/internaltest/4700364795587048983, Sanmill becomes searchable and accessible in the Play Store. However, upon exiting the internal test, the app once again becomes unsearchable.

This situation indicates that there might be specific settings or requirements in the Google Play Store that are only being met when the app is in the internal testing phase. We are currently investigating this issue to understand the underlying cause and to ensure that Sanmill is visible and available to all users on the Play Store, regardless of their participation in the testing program.

**Comment by calcitem** [comment]
I've found the solution to the Sanmill app's visibility issue on LineageOS devices. The problem was caused by the "Visibility of product listings" setting in Google Play Console, set to perform device integrity checks. By switching to "No integrity check," the app will now be visible and downloadable on all devices, including those with LineageOS. Thank you for your help in resolving this.
